IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AACC_AACC_00000100' AND COLUMN_NAME = 'IsActive')
BEGIN
       ALTER TABLE AACC_AACC_00000100 ADD IsActive tinyint NOT NULL DEFAULT '1'
END