-- @#LONGSCRIPT#@

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MMNN_MMOO_00000100' AND COLUMN_NAME = 'USCName')
BEGIN
    EXEC sp_rename 'MMNN_MMOO_00000100.USCName', 'DEL_USCName';
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MMNN_MMOO_00000300' AND COLUMN_NAME = 'USCName')
BEGIN
    EXEC sp_rename 'MMNN_MMOO_00000300.USCName', 'DEL_USCName';
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MMNN_MMOO_00000400' AND COLUMN_NAME = 'USCName')
BEGIN
    EXEC sp_rename 'MMNN_MMOO_00000400.USCName', 'DEL_USCName';
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MMNN_OOPP_00000200' AND COLUMN_NAME = 'USCName')
BEGIN
    EXEC sp_rename 'MMNN_OOPP_00000200.USCName', 'DEL_USCName';
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MMNN_PPOO_00000300' AND COLUMN_NAME = 'USCName')
BEGIN
    EXEC sp_rename 'MMNN_PPOO_00000300.USCName', 'DEL_USCName';
END