-- @#LONGSCRIPT#@

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSHH_IINN_00000100' AND COLUMN_NAME = 'JEID')
BEGIN
    EXEC sp_rename 'SSHH_IINN_00000100.JEID', 'DEL_JEID';
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSHH_IINN_00000100' AND COLUMN_NAME = 'ByPercent')
BEGIN
    EXEC sp_rename 'SSHH_IINN_00000100.ByPercent', 'DEL_ByPercent';
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSHH_IINN_00000200' AND COLUMN_NAME = 'USCName')
BEGIN
    EXEC sp_rename 'SSHH_IINN_00000200.USCName', 'DEL_USCName';
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSHH_PPOO_00000200' AND COLUMN_NAME = 'USCName')
BEGIN
    EXEC sp_rename 'SSHH_PPOO_00000200.USCName', 'DEL_USCName';
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSHH_PPOO_00000300' AND COLUMN_NAME = 'USCName')
BEGIN
    EXEC sp_rename 'SSHH_PPOO_00000300.USCName', 'DEL_USCName';
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSHH_SSHH_00000200' AND COLUMN_NAME = 'USCName')
BEGIN
    EXEC sp_rename 'SSHH_SSHH_00000200.USCName', 'DEL_USCName';
END