-- @#LONGSCRIPT#@

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSAA_IINN_00000100' AND COLUMN_NAME = 'JEID')
BEGIN
    EXEC sp_rename 'SSAA_IINN_00000100.JEID', 'DEL_JEID';
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSAA_IINN_00000100' AND COLUMN_NAME = 'ByPercent')
BEGIN
    EXEC sp_rename 'SSAA_IINN_00000100.ByPercent', 'DEL_ByPercent';
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSAA_IINN_00000200' AND COLUMN_NAME = 'USCName')
BEGIN
    EXEC sp_rename 'SSAA_IINN_00000200.USCName', 'DEL_USCName';
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSAA_IINN_00000200' AND COLUMN_NAME = 'TrkRef')
BEGIN
    EXEC sp_rename 'SSAA_IINN_00000200.TrkRef', 'DEL_TrkRef';
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSAA_SSHH_00000200' AND COLUMN_NAME = 'USCName')
BEGIN
    EXEC sp_rename 'SSAA_SSHH_00000200.USCName', 'DEL_USCName';
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSAA_SSOO_00000200' AND COLUMN_NAME = 'USCName')
BEGIN
    EXEC sp_rename 'SSAA_SSOO_00000200.USCName', 'DEL_USCName';
END