-- @#LONGSCRIPT#@

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EEMM_EEMM_00000300')
BEGIN
	EXEC sp_rename EEMM_EEMM_00000300, DEL_EEMM_EEMM_00000300;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EEMM_EEMM_00000400' AND COLUMN_NAME = 'CurName')
BEGIN
    ALTER TABLE EEMM_EEMM_00000400 ADD CurName nvarchar(80) DEFAULT(N'') NOT NULL
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EEMM_EEMM_00000400' AND COLUMN_NAME = 'Accepted')
BEGIN
    EXEC sp_rename 'EEMM_EEMM_00000400.Accepted', 'Status';
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EEMM_EEMM_00000400' AND COLUMN_NAME = 'Closed')
BEGIN
    EXEC sp_rename 'EEMM_EEMM_00000400.Closed', 'DEL_Closed';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EEMM_EEMM_00000500' AND COLUMN_NAME = 'Provider')
BEGIN
    ALTER TABLE EEMM_EEMM_00000500 ADD Provider nvarchar(80) DEFAULT(N'') NOT NULL
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EEMM_EEMM_00000500' AND COLUMN_NAME = 'TrkRef')
BEGIN
    EXEC sp_rename 'EEMM_EEMM_00000500.TrkRef', 'CostAccount';
	ALTER TABLE EEMM_EEMM_00000500 ALTER COLUMN CostAccount nvarchar(40) NOT NULL;
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EEMM_EEMM_00000500' AND COLUMN_NAME = 'ExpenseName')
BEGIN
    EXEC sp_rename 'EEMM_EEMM_00000500.ExpenseName', 'DEL_ExpenseName';
	ALTER TABLE EEMM_EEMM_00000500 ADD Descrip nvarchar(max) DEFAULT(N'') NOT NULL
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EEMM_EEMM_00000500' AND COLUMN_NAME = 'USCName')
BEGIN
	EXEC sp_rename 'EEMM_EEMM_00000500.USCName', 'DEL_USCName';
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EEMM_EEMM_00000500' AND COLUMN_NAME = 'TrkQ')
BEGIN
	EXEC sp_rename 'EEMM_EEMM_00000500.TrkQ', 'DEL_TrkQ';
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EEMM_EEMM_00000500' AND COLUMN_NAME = 'PrjPeriod')
BEGIN
	EXEC sp_rename 'EEMM_EEMM_00000500.PrjPeriod', 'DEL_PrjPeriod';
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EEMM_EEMM_00000500' AND COLUMN_NAME = 'CType')
BEGIN
	EXEC sp_rename 'EEMM_EEMM_00000500.CType', 'DEL_CType';
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EEMM_EEMM_00000500' AND COLUMN_NAME = 'SrvcOrdRef')
BEGIN
	EXEC sp_rename 'EEMM_EEMM_00000500.SrvcOrdRef', 'DEL_SrvcOrdRef';
END

-- Update automatic references
UPDATE SYST_AARR_00000200 SET FType = 6, FValue = '', FIniVal = '', FEndVal = '', FZeros = 1, FChars = 0 
WHERE FOrder = 2 AND AtRName = 'EmployeeExpenses'

DECLARE
@RecID int

SET @RecID = (SELECT TOP(1) RecID FROM SYST_AARR_00000200 ORDER BY RecID DESC)

SET @RecID = @RecID + 1
INSERT INTO SYST_AARR_00000200 
(AtRName, TblRef, FOrder, FType, FValue, FIniVal, FEndVal, FZeros, FChars, RecState, CrtUser, LastUser, Owner, RecEnt, RecOU, RecSec, CntID, RecID) VALUES 
('EmployeeExpenses', 'EEMM_EEMM_00000400', 3, 1, '_', '', '', 0, 0, 0, 'SYSADM', 'SYSADM', 'SYSADM', 'ment', 'ment', 1, 0, @RecID)      

SET @RecID = @RecID + 1
INSERT INTO SYST_AARR_00000200 
(AtRName, TblRef, FOrder, FType, FValue, FIniVal, FEndVal, FZeros, FChars, RecState, CrtUser, LastUser, Owner, RecEnt, RecOU, RecSec, CntID, RecID) VALUES 
('EmployeeExpenses', 'EEMM_EEMM_00000400', 4, 5, '', '', '', 0, 2, 0, 'SYSADM', 'SYSADM', 'SYSADM', 'ment', 'ment', 1, 0, @RecID)