-- @#LONGSCRIPT#@

-- If original database version < 30.02.02 AND COU layer is not loaded
-- Intrastat fileds and tables are already present in SYS, so mark them as deleted.
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSHH_SSPP_00000100' AND COLUMN_NAME = 'DelTerms')
BEGIN
    EXEC sp_rename 'SSHH_SSPP_00000100.DelTerms', 'DEL_DelTerms', 'COLUMN'
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSHH_SSPP_00000100' AND COLUMN_NAME = 'OperationType')
BEGIN
    EXEC sp_rename 'SSHH_SSPP_00000100.OperationType', 'DEL_OperationType', 'COLUMN'
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSHH_IINN_00000100' AND COLUMN_NAME = 'DelTerms')
BEGIN
    EXEC sp_rename 'SSHH_IINN_00000100.DelTerms', 'DEL_DelTerms', 'COLUMN'
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSHH_IINN_00000100' AND COLUMN_NAME = 'Port')
BEGIN
    EXEC sp_rename 'SSHH_IINN_00000100.Port', 'DEL_Port', 'COLUMN'
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSHH_IINN_00000100' AND COLUMN_NAME = 'NatTrans')
BEGIN
    EXEC sp_rename 'SSHH_IINN_00000100.NatTrans', 'DEL_NatTrans', 'COLUMN'
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSHH_IINN_00000100' AND COLUMN_NAME = 'ModTrans')
BEGIN
    EXEC sp_rename 'SSHH_IINN_00000100.ModTrans', 'DEL_ModTrans', 'COLUMN'
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSHH_IINN_00000100' AND COLUMN_NAME = 'StatReg')
BEGIN
    EXEC sp_rename 'SSHH_IINN_00000100.StatReg', 'DEL_StatReg', 'COLUMN'
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSHH_IINN_00000100' AND COLUMN_NAME = 'OperationType')
BEGIN
    EXEC sp_rename 'SSHH_IINN_00000100.OperationType', 'DEL_OperationType', 'COLUMN'
END

