-- @#LONGSCRIPT#@

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSHH_SSPP_00000100' AND COLUMN_NAME = 'DEL_DelTerms')
BEGIN
	exec sp_executesql N'UPDATE SSHH_SSPP_00000100 SET DelTerms = DEL_DelTerms'
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSHH_SSPP_00000100' AND COLUMN_NAME = 'DEL_OperationType')
BEGIN
	exec sp_executesql N'UPDATE SSHH_SSPP_00000100 SET OperationType = DEL_OperationType'
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSHH_IINN_00000100' AND COLUMN_NAME = 'DEL_DelTerms')
BEGIN
	exec sp_executesql N'UPDATE SSHH_IINN_00000100 SET DelTerms = DEL_DelTerms'
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSHH_IINN_00000100' AND COLUMN_NAME = 'DEL_Port')
BEGIN
	exec sp_executesql N'UPDATE SSHH_IINN_00000100 SET Port = DEL_Port'
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSHH_IINN_00000100' AND COLUMN_NAME = 'DEL_NatTrans')
BEGIN
	exec sp_executesql N'UPDATE SSHH_IINN_00000100 SET NatTrans = DEL_NatTrans'
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSHH_IINN_00000100' AND COLUMN_NAME = 'DEL_ModTrans')
BEGIN
	exec sp_executesql N'UPDATE SSHH_IINN_00000100 SET ModTrans = DEL_ModTrans'
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSHH_IINN_00000100' AND COLUMN_NAME = 'DEL_StatReg')
BEGIN
	exec sp_executesql N'UPDATE SSHH_IINN_00000100 SET StatReg = DEL_StatReg'
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSHH_IINN_00000100' AND COLUMN_NAME = 'DEL_OperationType')
BEGIN
	exec sp_executesql N'UPDATE SSHH_IINN_00000100 SET OperationType = DEL_OperationType'
END