-- @#LONGSCRIPT#@
-- Actualizar nuevos campos
DECLARE @ComRef nvarchar(40)
DECLARE @ComName nvarchar(255)
DECLARE CurOpp CURSOR FOR 
SELECT DISTINCT ComRef FROM OOPP_OOPP_00000200

OPEN CurOpp
FETCH NEXT FROM CurOpp INTO @ComRef
WHILE @@FETCH_STATUS = 0
   BEGIN
		SELECT @ComName=ComName FROM CCOO_CCOO_00000100 WHERE ComRef=@ComRef
    	UPDATE OOPP_OOPP_00000200 SET ComName=@ComName WHERE ComRef=@ComRef
		FETCH NEXT FROM CurOpp INTO @ComRef
   END
CLOSE CurOpp
DEALLOCATE CurOpp

DECLARE CurOpp1 CURSOR FOR 
SELECT DISTINCT ComRef FROM OOPP_OOPP_00000300

OPEN CurOpp1
FETCH NEXT FROM CurOpp1 INTO @ComRef
WHILE @@FETCH_STATUS = 0
   BEGIN
		SELECT @ComName=ComName FROM CCOO_CCOO_00000100 WHERE ComRef=@ComRef
    	UPDATE OOPP_OOPP_00000300 SET ComName=@ComName WHERE ComRef=@ComRef
		FETCH NEXT FROM CurOpp1 INTO @ComRef
   END
CLOSE CurOpp1
DEALLOCATE CurOpp1
