-- @#LONGSCRIPT#@

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MMNN_MMOO_00000100' AND COLUMN_NAME = 'MnORoot')
BEGIN
    UPDATE MMNN_MMOO_00000100 SET MnORoot = MnORef WHERE MnORoot = ''
END