-- @#LONGSCRIPT#@

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RRSS_RRSS_00000200' AND COLUMN_NAME = 'TblRef')
BEGIN
    EXEC sp_rename 'RRSS_RRSS_00000200.TblRef', 'DEL_TblRef', 'COLUMN'
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RRSS_RRSS_00000200' AND COLUMN_NAME = 'RecordID')
BEGIN
    EXEC sp_rename 'RRSS_RRSS_00000200.RecordID', 'DEL_RecordID', 'COLUMN'
END
