
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'lantek360MapLog' AND COLUMN_NAME = 'Message' AND DATA_TYPE = 'nvarchar' AND CHARACTER_MAXIMUM_LENGTH = -1)
BEGIN
    ALTER TABLE Lantek360MapLog ALTER COLUMN Message NVARCHAR(MAX) NOT NULL
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'lantek360MapLog' AND COLUMN_NAME = 'CodeMessage' AND DATA_TYPE = 'smallint')
BEGIN
    ALTER TABLE Lantek360MapLog ADD CodeMessage smallint NOT NULL default -1
END