-- @#LONGSCRIPT#@

DROP INDEX [PK_CCLL_EEXX_00000200] ON [dbo].[CCLL_EEXX_00000200]

ALTER TABLE CCLL_EEXX_00000200 ALTER COLUMN TblRef nvarchar(50) NOT NULL


CREATE NONCLUSTERED INDEX [PK_CCLL_EEXX_00000200] ON [dbo].[CCLL_EEXX_00000200]
(
	[CalName] ASC,
	[TblRef] ASC,
	[RecordID] ASC,
	[Date] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

