-- @#LONGSCRIPT#@

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSPP_SSPP_00000100' AND COLUMN_NAME = 'PayDay1')
BEGIN
    EXEC sp_rename 'SSPP_SSPP_00000100.PayDay1', 'DEL_PayDay1';
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSPP_SSPP_00000100' AND COLUMN_NAME = 'PayDay2')
BEGIN
    EXEC sp_rename 'SSPP_SSPP_00000100.PayDay2', 'DEL_PayDay2';
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSPP_SSPP_00000100' AND COLUMN_NAME = 'PayDay3')
BEGIN
    EXEC sp_rename 'SSPP_SSPP_00000100.PayDay3', 'DEL_PayDay3';
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSPP_SSPP_00000500' AND COLUMN_NAME = 'CarName')
BEGIN
    EXEC sp_rename 'SSPP_SSPP_00000500.CarName', 'DEL_CarName';
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSPP_SSPP_00000500' AND COLUMN_NAME = 'SCAccount')
BEGIN
    EXEC sp_rename 'SSPP_SSPP_00000500.SCAccount', 'DEL_SCAccount';
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSPP_SSPP_00000500' AND COLUMN_NAME = 'SPAccount')
BEGIN
    EXEC sp_rename 'SSPP_SSPP_00000500.SPAccount', 'DEL_SPAccount';
END

IF EXISTS  (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SSPP_TTRR_00000200' AND COLUMN_NAME = 'USCName')
BEGIN
    EXEC sp_rename 'SSPP_TTRR_00000200.USCName', 'DEL_USCName';
END